sonar.organization=fiatty
sonar.projectKey=FiatTy_pccth_code_review_web-dev
sonar.projectName=pccth_code_review_web-dev

sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/assets/**,**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx

sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx

sonar.coverage.exclusions=**/*
sonar.cpd.exclusions=**/*